### ISSUE TITLE
[Need Help with Error] /usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/protobuf.rb:49:in `require': Error loading shared library

### ISSUE THREAD

**Issue by raviwarrier** [waschinski/photo-stream#77]
Hello, I just tried installing PS and am getting this error in my log when I try to run the container.

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)

/usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/protobuf.rb:51:in `require': cannot load such file -- google/protobuf_c (LoadError)

/usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/protobuf.rb:49:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/3.1/protobuf_c.so) - /usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/3.1/protobuf_c.so (LoadError)

I followed the instructions in Readme to install it. I tried going through all the issues posted and couldn't understand if any of those pertain to my problem. I also installed jekyll (sudo apt install jekyll - sorry, I am a novice, so please let me know if this wasn't the way) 

My config details are as follows:
Installed on: RPI 4b arm64
Docker version 23.0.2, build 569dd73

**Comment by Thoscellen** [comment]
Hello, same with my Mac M1.

```
photo-stream  | Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
photo-stream  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
photo-stream  | /usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/protobuf.rb:51:in `require': cannot load such file -- google/protobuf_c (LoadError)
photo-stream  |         from /usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
photo-stream  |         from /usr/local/bundle/gems/google-protobuf-3.22.2-aarch64-linux/lib/google/protobuf.rb:48:in `<top (required)>'
```

**Comment by iHarshad** [comment]
Changed the Ruby image to `ruby:3.1.3` (base image is Debian) to check what was happening. 

I got an error for the `vips` package. After installing `libvips`, the project was able to compile and run the Jekyll server command successfully.
<img width="1035" alt="image" src="https://github.com/waschinski/photo-stream/assets/8861290/a6487f43-d795-471e-a0c2-ff2f8b4f4635">

The other change was to pin `jekyll_image_processing` plugin to around Ruby 3.1.3 release date.
```Gemfile
gem "jekyll_image_processing", git: "https://github.com/benubois/jekyll_image_processing", ref: "e4a2626"
```
